---
abstract: 'return name and handle of a temporary file safely'
author:
  - 'Tim Jenness <tjenness@cpan.org>'
build_requires:
  Cwd: 0
  Test::More: 0
configure_requires:
  Module::Build: 0.36
dynamic_config: 1
generated_by: 'Module::Build version 0.3901, CPAN::Meta::Converter version 2.120630'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: File-Temp
provides:
  File::Temp:
    file: lib/File/Temp.pm
    version: 0.22_90
  File::Temp::Dir:
    file: lib/File/Temp.pm
    version: 0
requires:
  Fcntl: 1.03
  File::Path: 2.06
  File::Spec: 0.8
resources:
  homepage: http://github.com/Perl-Toolchain-Gang/File-Temp/tree/master
  license: http://dev.perl.org/licenses/
  repository: git://github.com/Perl-Toolchain-Gang/File-Temp.git
version: 0.22_90
