---
abstract: 'return name and handle of a temporary file safely'
author:
  - 'Tim Jenness <tjenness@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.17
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300039, CPAN::Meta::Converter version 2.132810'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: File-Temp
no_index:
  directory:
    - t
    - xt
    - examples
    - corpus
  package:
    - DB
provides:
  File::Temp:
    file: lib/File/Temp.pm
    version: 0.2303
  File::Temp::Dir:
    file: lib/File/Temp.pm
    version: 0.2303
requires:
  Exporter: 5.57
  Fcntl: 1.03
  File::Path: 2.06
  File::Spec: 0.8
  parent: 0.221
  perl: 5.006
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=File-Temp
  homepage: https://github.com/Perl-Toolchain-Gang/File-Temp
  repository: https://github.com/Perl-Toolchain-Gang/File-Temp.git
version: 0.2303
x_authority: cpan:TJENNESS
x_contributors:
  - 'Ben Tilly <btilly@gmail.com>'
  - 'David Golden <dagolden@cpan.org>'
  - 'David Steinbrunner <dsteinbrunner@pobox.com>'
  - 'Ed Avis <eda@linux01.wcl.local>'
  - 'James E. Keenan <jkeen@verizon.net>'
  - 'Karen Etheridge <ether@cpan.org>'
  - 'Kevin Ryde <user42@zip.com.au>'
  - 'Olivier Mengue <dolmen@cpan.org>'
  - 'Peter John Acklam <pjacklam@online.no>'
  - 'Peter Rabbitson <ribasushi@cpan.org>'
