use strict;
use warnings;
use Test::More;

# generated by Dist::Zilla::Plugin::Test::PodSpelling 2.004003
eval "use Test::Spelling 0.12; use Pod::Wordlist::hanekomu; 1" or die $@;


add_stopwords(<DATA>);
all_pod_files_spelling_ok( qw( bin lib  ) );
__DATA__
APIs
Acklam
Christiansen
EXLOCK
NFS
OpenBSD
POSIX
Ryde
Tilly
TopSystemUID
UNLINK
chdir'ed
cmpstat
destructor
dirname
endeavour
et
isa
newdir
numifies
unix
unlink
unlinked
unlinking
Tim
Jenness
tjenness
and
the
UK
Particle
Physics
Astronomy
Research
Council
lib
File
Temp
